### ISSUE TITLE
feature request : bitmap based window decoration themes

### ISSUE THREAD

**Issue by aspizu** [phillbush/shod#11]
where each part of the decoration has a bitmap image, also would allow for rounded corners

xfwm themes work in this way

**Comment by phillbush** [comment]
Hmm,

Shod had image-based themes in the past, in an early version.  
This was its theme image (converted from `.xpm` to `.png`):

![theme](https://user-images.githubusercontent.com/63266536/187311622-20fd69fb-b778-4ec0-9d2e-10d30b19df9e.png)

When invoked, shod did first read the pixmap file and split it into several parts for each section of the decoration (edges, corners, buttons, titlebars, etc). But the code was so convoluted and hard to maintain that I later moved into a color-based motif-only theme.

Now, shod theming works just like `mwm(1)` (motif window manager): you cannot change the decoration style, you can only change its colors. I have never used anything other than the motif theme on shod, so this has never been a drawback for me.

I really do not want to get the old code for image-based theming back, sorry...

If you show me a better theme style/shape other than motif's, I may think of a way to support it without requiring moving back to a pixmap-based theming.

On round corners: that would need a compositor, and different compositors do round corners in different ways with differently looking results... And also, I do not want to force another application to the user; I prefer to let the user free to choose whether or not to do compositing.

**Comment by aspizu** [comment]
Thank you, Do you still have this old version ( with bitmap themes ) so I can play around with it?

**Comment by aspizu** [comment]
0d640b2f6dffb1ad22a766cca3127b84a51e8cb8 ?

**Comment by phillbush** [comment]
Yes, this was the commit that moved to color-based theming.  
Much have changed since then however, so I do not recommend using it.
