### ISSUE TITLE
shod stopped working after update

### ISSUE THREAD

**Issue by aspizu** [phillbush/shod#12]
#### Updated shod to latest
* `git pull`
* `make -j16`
* `sudo make install`
* restarted

#### Now shod starts but issues
* No x window is visible
* sxhkd stopped working completely
* all x apps ignore killing

#### If shod is started from an already running X app, i.e not from ~/.xinitrc it works as normal
This is weird and as a work around i've set Ctrl+O in sxhkd to launch shod.

**Comment by phillbush** [comment]
Try to call shod in your ~/.xinitrc with a `</dev/null` at the end of the line, like
```
shod </dev/null
```
or 
```
exec shod </dev/null
```

Does it work now?

**Comment by aspizu** [comment]
`shod </dev/null` and `exec shod </dev/null` both just don't start shod at all.

**Comment by aspizu** [comment]
Yes, thank you.
