### ISSUE TITLE
close button for all tabs

### ISSUE THREAD

**Issue by aspizu** [phillbush/shod#18]
currently the close button is always top-right and closes the focused tab, instead have a close button for every tab. allowing to close tabs without having to switch to them first. this also prevents ambiguity when someone might think that the close button closes the tab the button is next to

**Comment by phillbush** [comment]
The geometry of container elements (tabs, buttons, handles, etc) is hardcoded in the code. Changing that would require lots of rewriting and rework.

This design is not uncommon though. That's where the close button is placed on some web browsers like [Seamonkey](https://www.seamonkey-project.org/):
![tabbutton](https://user-images.githubusercontent.com/63266536/187806320-f1290629-9817-4e3d-ab34-59c1a93569ba.png)
