### ISSUE TITLE
shod or shod2

### ISSUE THREAD

**Issue by 0323pin** [phillbush/shod#2]
Olá,

Eu mantenho o pacote de `shod` para a NetBSD que importei no final de Agosto, https://pkgsrc.se/wm/shod

Será que você recomenda que eu substitua esse pacote por um novo `shod2`? Como chamar o programa nesse caso, `shod2` ou simplesmente `shod`? O executável é `shod` mesmo, não é?

Obrigado por um pouco mais de imformacão se for possivel.

/pin

**Comment by phillbush** [comment]
Olá, o nome do programa e do executável continuam sendo `shod`.
Como as mudanças no código fonte foram significativas, preferi lançar a nova versão em um novo repositório.

Eu renomeei este repositório para `shod` e o repositório antigo (que agora está arquivado), renomeei para `shod-old`.

Como não manterei mais a primeira versão, você pode deixar o pacote com o nome `shod` mas substituir a fonte do pacote para este repositório.

**Comment by 0323pin** [comment]
Ok, agora està tudo mais claro, obrigado.
Fechando ;)
