### ISSUE TITLE
killing panels crashes shod

### ISSUE THREAD

**Issue by aspizu** [phillbush/shod#21]
### recreate
1. launch any panel such as tint2, polybar
2. kill the panel
3. shod crashes

**Comment by phillbush** [comment]
I forgot to assign the type of object to the panel/dock type (`TYPE_DOCK`).  
Fixed by [b767a97](https://github.com/phillbush/shod/commit/b767a9785ec4e4483866e384c58aaf023eb17057).  
(it was just a single line fix lol)

**Comment by aspizu** [comment]
thank you
