### ISSUE TITLE
increase tiling reparent window drop area

### ISSUE THREAD

**Issue by aspizu** [phillbush/shod#22]
it is hard to drag-drop the window to tile it
and also show a highlight where the window would appear

**Comment by phillbush** [comment]
With [19fd905](https://github.com/phillbush/shod/commit/19fd9059b377dae9c1266ab18c9bb502c7988dd8) the mouse cursor now changes depending on where you are drag-dropping a window to (dragging it into a vertical division of a container turns the cursor into a horizontal arrow, for example).  
So, if the cursor changes (indicating that tiling will occur) you can release the mouse button and drop the window.

**Comment by aspizu** [comment]
the titlebar becomes a square, is this intentional?

**Comment by phillbush** [comment]
Yeah, titlebars can be very large and they hide the drop area behind it.  
Then I decided to replace it with an icon indicating that the drag-and-drop is in action.
