### ISSUE TITLE
fullscreen mode should only show the single window with no decorations

### ISSUE THREAD

**Issue by aspizu** [phillbush/shod#24]
dont show other windows

**Comment by phillbush** [comment]
I don't understand what you want to mean.  
Are you saying that, on a full screen container, the focused window inside it should occupy the entire container, even if there are other windows tiled with it?

**Comment by aspizu** [comment]
yes

**Comment by BanchouBoo** [comment]
Might be nice if you could do both, make a distinction between fullscreening a window and fullscreening/maximizing a container.

As an example, I use mpv to watch Twitch streams via streamlink and then I use chatterino for chat, putting those windows together in a container makes sense and is nice, but when I do that and try to fullscreen mpv it now does the container instead. Same thing for if you're watching a video in a web browser and try to fullscreen it. Definitely would prefer it to fullscreen *just* the relevant window, then the current functionality can be included as a separate thing you can do.

**Comment by phillbush** [comment]
I personally do not use fullscreen a lot, and when I do (while playing a movie on TV for example) there's only a single window in the container, so it gets fullscreen with the titlebar hidden.
I have never kinda needed such feature, therefore it not being implemented although I thought on it when I first implemented containers.
I am implementing it now.
