### ISSUE TITLE
feature request: `shodc reload`

### ISSUE THREAD

**Issue by sewnie** [phillbush/shod#29]
relevant/similar dwm patches: [restartsig](https://dwm.suckless.org/patches/restartsig/dwm-restartsig-20180523-6.2.diff) [preserveonrestart](https://dwm.suckless.org/patches/preserveonrestart/dwm-preserveonrestart-6.3.diff), bspwm has something similar as well.

i believe shod lets out X atoms about the desktops and windows.

**Comment by sewnie** [comment]
this can be quite useful when shod is being configured via Xresources.

**Comment by phillbush** [comment]
> this can be quite useful when shod is being configured via Xresources.

Shod already reloads itself when the X resources database changes.
This is not the optimal solution tho. The best solution would be for shod to reload itself only when a `Shod*` or `shod*` resource has changed.
The way it works now, it reloads every time the resource database changes, even when what you changed was an unrelated resource for, say, XTerm.

**Comment by sewnie** [comment]
Why i thought `reload` was needed was because shod does indeed know of the X resources change, however if for example i changed the `dockpos` for a few dockapps i will have to reload the dockapps themselves, as shod will not re-place them.

that's all.
