### ISSUE TITLE
tabbed window going fullscreen goes haywire

### ISSUE THREAD

**Issue by sewnie** [phillbush/shod#30]
https://user-images.githubusercontent.com/47404953/212524789-714704ff-cfe2-4f12-8dbc-63a4eb68e746.mp4

on my end, there is tons of flickering.

**Comment by phillbush** [comment]
I could not reproduce the error here.
Does that only occur with Firefox?
Firefox usually takes some time to respond to window resizes.
Can you try that on other programs?

**Comment by sewnie** [comment]
A recent commit has fixed it.
