### ISSUE TITLE
Dragging windows feels low frame rate on 120Hz 2.8K display

### ISSUE THREAD

**Issue by aspizu** [phillbush/shod#33]
I have picom running

**Comment by phillbush** [comment]
By "dragging" you mean moving a window around or moving a detached title bar in a drag-and-drop motion?

**Comment by aspizu** [comment]
moving a window around

**Comment by sewnie** [comment]
yep can reproduce lol. the default 'redraw' rate is `64`.

**Comment by BanchouBoo** [comment]
You can make it smoother by using my PR above ~or by changing the `MOVETIME` and `RESIZETIME` macros in `shod.h`~ **EDIT:** PR merged, you can set it in `config.c` during compilation or in your Xresources file (see man page for details). At 120hz you'd want to use a value of 8 if you want it as smooth as possible.
