### ISSUE TITLE
What is the correct syntax for Shod's options?

### ISSUE THREAD

**Issue by ghost** [phillbush/shod#4]
Idiotic question, but how do I set the various options for Shod? I looked at the wiki and tried 'shod -m Mod4' and 'shod [-m Mod4]' but neither work, so what is the correct format?

**Comment by phillbush** [comment]
The wiki was out of date and the -m option had been removed.  
I re-added the -m option and updated the wiki to the latest version of the manual.  
The -m option should work now.
