### ISSUE TITLE
Some feedback

### ISSUE THREAD

**Issue by webbongithub** [phillbush/shod#41]
I don't want to create a bunch of small issues, since a lot of these are closely related and these are mostly annoyances rather than anything important. I don't expect these to be implemented, and frankly I should do a patch for these things, but this feedback might be helpful to you.

## disablable titlebars

I use two small monitors where screen real estate is precious, especially since I have things scaled up. Setting the title bar's width to nothing prevents you from manipulating containers. Having the functionality of the titlebar moved to another button, say middle click while hovering on the window border would be a good solution to this. The close button could be a middle click of the top right corner, and the top left could be container manipulation. That's one idea though, I'm sure there's probably a more elegant solution.

## half bartmode

I don't usually use bartmode, but with shod it's necessary if you have overlapping windows regularly. It would be nice to have an option to not bring windows to the top in sloppy mode. Navigating all the windows can be a nightmare because as you move to one window another will be brought to the top, and you have to do this whole dance with layers and hoping you don't activate anything. Being able to hover over a window to focus it, but click to bring it to the top would be nice. 

## bartmode  granularity

A nice feature that would work hand-in-hand with the last one is more granular options for bartmode. For example, within a container bartmode is unnecessary because with tiling nothing overlaps. The same applies to monitors, being able to move with sloppy mode between monitors but leave top-level windows in bartmode would rock.

**Comment by webbongithub** [comment]
Oh by the way, bartmode == not-sloppy-mode.

**Comment by phillbush** [comment]
> disablable titlebars

Titlebars are necessary for tabbing. Hiding them would require nontrivial change on the code and how shod displays the title bars.

> half bartmode

Do you mean that the focus-follow-mouse scheme should not raise a container to the top of others?
That is the default behavior on the click-to-focus scheme, and focus-follow-mouse just replicates it.
I can make FFM not raise a container unless a mouse button is pressed.

> bartmode granularity

Do you mean to configure either the focus-follow-mouse or click-to-focus differently for both container-focusing and tile-focusing?
That can be done. And that is what Plan 9 does with rio and acme: rio manages stacked/floating windows with click-to-focus, while acme manages tiled windows with focus-follow-mouse. The other way around could also be feasible.

**Comment by webbongithub** [comment]
> Titlebars are necessary for tabbing. Hiding them would require nontrivial change on the code and how shod displays the title bars.

I didn't think of this, you're right.

> Do you mean that the focus-follow-mouse scheme should not raise a container to the top of others?
That is the default behavior on the click-to-focus scheme, and focus-follow-mouse just replicates it.
I can make FFM not raise a container unless a mouse button is pressed.

Yeah, pretty much.

> Do you mean to configure either the focus-follow-mouse or click-to-focus differently for both container-focusing and tile-focusing?

Yeah.

**Comment by phillbush** [comment]
Sloppy focus do not raise the container anymore.

I added a `-S` flag for sloppy focus between tiles in the same container; and kept the `-s` flag for sloppy focus between different containers.

So, to reproduce Plan 9's focus system (click-to-focus between rio containers, sloppy focus between acme sub-windows), just call shod as `shod -S`.
