### ISSUE TITLE
Feature Request: Acme Titlebar theme

### ISSUE THREAD

**Issue by wesbluemarine** [phillbush/shod#45]
Would it be possible to change the look of the title bar to look like acme?

**Comment by phillbush** [comment]
You can change the color of the decoration and titlebar around windows with a triplet of colors: a light one, a middle one and a dark one.  For example, for the active window, the triplet is `activeTopShadowColor, activeBackground, activeBottomShadowColor`, which defaults to a light, mid, and dark blue.
The same works for inactive and urgent containers.

The titlebar, however is colored the same as the decoration.

**Comment by wesbluemarine** [comment]
Would it be possible to change also the border width?

**Comment by phillbush** [comment]
> Would it be possible to change also the border width?

Set the `shod.borderWidth` X resource to the size you want in pixels.
More information on the manual.
