### ISSUE TITLE
Alt-tab doesn't work sometimes--with very difficult failure mode

### ISSUE THREAD

**Issue by daym** [phillbush/shod#47]
Because Mod2 is often num lock and shod tries to not match on modifier mod2, it's only possible to alt-tab when num lock is off.

Neither my laptop nor my external keyboard have num lock (or a numeric block) so that was... difficult to figure out. Lots of gdb.

I wonder whether it would be possible to have shod figure out what those locks are and ignore them.

**Comment by phillbush** [comment]
Sorry about that. I use a laptop without keypad, so NumLock is never active here.

Quoting the commit message:

> Grabbing a key with a certain modifier combination makes the client get events for that key ONLY when the same modifier combination is applied. Grabbing Super+Alt only makes shod get events for Super+Alt, not Super+Alt+NumLock.
>
> This commit also grab lock modifiers together with the primary modifier.
>
> It may brake a workflow that uses non-default lock modifiers.  Like, if you set Control to work lock-like (one press to activate, another press to disactivate) rather than shift-like (press to activate, release to disactivate), you are on your own[1]
>
> [1]: https://xkcd.com/1172/
