### ISSUE TITLE
DockApp detection could be better

### ISSUE THREAD

**Issue by daym** [phillbush/shod#48]
Currently, shod only uses Withdrawn to detect dockapps.

It would be better to also match the class "DockApp".

See also https://github.com/psychon/x11rb/issues/848 for why not (just) Withdrawn.

**Comment by phillbush** [comment]
Your proposal uses the class part of the `WM_CLASS` property, which is mostly used for applications to indicate the application group, vendor or class.

For example, Seamonkey (an Internet suite with browser, mail agent, news reader, etc) sets the class of its `WM_CLASS` to `"SeaMonkey"`, and distinguishes between the web browser window and the mail client window with the `"Navigator"` and `"Mail"` name part of its `WM_CLASS` property, respectively. Gimp, in its multi-window mode, also does the same to distinguish between the main canvas window and the palette window.

What specifies the type of the window (whether it is a normal application, a popup menu, a dialog window, a notification window, etc) is the [`_NET_WM_WINDOW_TYPE` property](https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html#idm45698775076592) (specified by the EWMH protocol, invented after ICCCM and WindowMaker's hack).

**Comment by daym** [comment]
I see what you mean.

But I'm just trying to make the dock and the dockapp detect each other. Since this is all like 1997 technology, changing the protocol on how this is done is not really practical.

I've checked WindowMaker, fluxbox, openbox and icewm and they all have something like 

        ./src/wmclient.cc:        (fClassHint.res_class && 0 == strcmp(fClassHint.res_class, "DockApp")) ||

in order to detect dockapps, among other ways.

About _NET_WM_WINDOW_TYPE: Yeah, there's a _NET_WM_WINDOW_TYPE_DOCK, but no _NET_WM_WINDOW_TYPE_DOCKAPP, right?

**Comment by phillbush** [comment]
Oh, I see.
I thought you were proposing a new window type, which would make more sense for `_NET_WM_WINDOW_TYPE`.
I just checked the wmaker source code; that seems to be yet another WindowMaker hack predating EWMH, or something like that.
I'm going to merge your PR :)
