### ISSUE TITLE
Feedback: Redraws while dragging feel slow

### ISSUE THREAD

**Issue by Hammster** [phillbush/shod#6]
Hi there I love how shod works! Great job on it! ❤️ 

The only issue is that dragging feels slow, I lack the skill to figure out what part of the code could be the culprit, but if I compare the performance to for example https://github.com/morgant/mlvwm (hard fork of fvwm 1.x) it's rather slow when it comes to drawing the window while dragging. 

I'm running it from WSL btw which also works very well. So this maybe something you don't even consider but mlvwm for comparison has no issue drawing at my monitors refresh rate.

![explorer_N6NgUlTG7l](https://user-images.githubusercontent.com/1093709/160212814-b3443455-c6b3-4ca9-b24a-e9600968eb63.png)

**Comment by phillbush** [comment]
> Hi there I love how shod works! Great job on it! 

Thanks!

> The only issue is that dragging feels slow, I lack the skill to figure out what part of the code could be the culprit, but if I compare the performance to for example https://github.com/morgant/mlvwm (hard fork of fvwm 1.x) it's rather slow when it comes to drawing the window while dragging.
> 
> I'm running it from WSL btw which also works very well. So this maybe something you don't even consider but mlvwm for comparison has no issue drawing at my monitors refresh rate.

By dragging you mean moving a container/window with the mouse left-button?  
If it is, I had a similar problem for resizing a container. The solution was to set a frame rate for redrawing it.  
I never had this problem for moving, so I had not implemented the same solution for such operation, only for resizing.

I implemented the redrawing frame rate for moving  in the last commit.  
Does this fix the problem for you?

**Comment by Hammster** [comment]
Sadly it did not improve the framerate it's now only running in 30FPS (since 1/32th of a second, great for the battery though), also tried out setting both `RESIZETIME` and `MOVETIME` to 0 just to see if this without any limitation since my hardware should really not have a issue with that. But sadly it did not fix the initial issue.

Oh also `${INSTALL}` in the makefile change that also was commited isn't working for me so i had to change that back to `install` to get it building

**Comment by phillbush** [comment]
`containerincrmove()`, the function that is called every time the mouse moves, called `containermoveresize()`, which moves and resizes the container and all its subwindows. This may be what is slowing down in your system.
All this moving and resizing is really not necessary, since all what is moving is the container as a whole, not its subwindows.  
I simplified it to a single call to `XMoveWindow` in the last commit.

> Oh also `${INSTALL}` in the makefile change that also was commited isn't working for me so i had to change that back to `install` to get it building

Hmm. I changed the Makefile after reading GNU Make guidelines on writing a Makefile.  
It tells us to use variables like `${INSTALL}`, `${CC}` and `${YACC}` rather than hardcode `install`, `cc` and `yacc` (so the user can use `gcc` rather than `cc` and `bison` in place of `yacc`), but it seems that your `make` implementation does not set the `INSTALL` variable.

**Comment by Hammster** [comment]
I investigated a bit by writing the `ev.xmotion.time` into a log, the time between event's is 16ms to 15ms (~60FPS). I think this is the issue more or less, I don't know if that is actually something you can fix from WM side. 

I tried configuring it with `xrandr` but this isn't working since this is a setup where vcxsrv is driving my window (which is set to 144hz there). So maybe this is a issue only for machines where the x server and client are not the same OS/Machine. But i have to dive into the x documentation for that.

<details>
  <summary>Frametime Log (open to view)</summary>
  
  print out from `ev.xmotion.time` in between frames within the `mousemove` function
  
  ```bash
X 395496812
X 395496828
X 395496843
X 395496859
X 395496875
X 395496890
X 395496890
X 395496906
X 395496921
X 395496921
X 395496937
X 395496953
X 395496953
X 395496968
X 395496984
X 395496984
X 395497000
X 395497015
X 395497015
X 395497031
X 395497046
X 395497046
X 395497062
X 395497078
X 395497078
X 395497093
X 395497109
X 395497109
X 395497125
X 395497140
X 395497140
X 395497156
X 395497171
X 395497171
X 395497187
X 395497203
X 395497218
X 395497234
X 395497234
X 395497250
X 395497265
X 395497281
X 395497296
X 395497296
X 395497312
X 395497328
X 395497328
X 395497343
X 395497359
X 395497375
X 395497390
X 395497406
X 395497421
X 395497421
X 395497437
X 395497453
X 395497453
X 395497468
X 395497484
X 395497500
X 395497515
X 395497515
X 395497531
X 395497546
  ```
  
</details>

I'm also going to give this a spin from a normal linux install just to confirm this isn't a issue with a proper 144hz configured X from a normal usecase, but this has to wait till tomorrow (2AM here)

Cheers :)

**Comment by Hammster** [comment]
Oh, I didn't comment afterwards.

Using a normal Linux install, it all worked out as it should, so this came down to the updates being locked to 60FPS by the system and not shod. 

Just going to say again it's great using shod, it has all the essential things I needed, especially after I was looking from some  *nix alternative to the haiku OS window management.
