### ISSUE TITLE
Minimizable containers

### ISSUE THREAD

**Issue by blk750** [phillbush/shod#7]
I think this is a cool window manager, although the ability to minimize containers would be nice.

**Comment by phillbush** [comment]
Shod can minimize containers.  
You can use either [wmctrl](http://tripie.sweb.cz/utils/wmctrl/) (which works in all EWMH-compliant window managers) or `shodc(1)`, shod's remote controller.

With `shodc(1)`, the following command either minimizes a visible container, or restores a minimized container:

```
shodc state -m <WINDOWID>
```

To list the window IDs, run the following command:

```
shodc list -l
```

In the `shodc list -l` output, if the fourth character of the first column is a `m`, the window is minimized; if it is a `-`, it is not minimized. For example, in the following output, one of the windows is in a minimized container:

```
---m-----       3       650x394+6+322   0x0340000a      0x0340000a      0x0340000a      ~ - ttyp4
---------       3       650x394+424+183 0x0200000a      0x0200000a      0x0200000a      ~ - ttyp3
```

The IDs are in the sixth column (`0x0340000a` and `0x0200000a` in the previous example cases).  
The fourth and fifth columns may have the same id if the window is the sole window in a container or is the focused window in a container.

**Comment by phillbush** [comment]
You can use a program like [sxhkd](https://github.com/baskerville/sxhkd) to map a keyboard shortcut to the minimize command.  You can also use a program like [xmenu](https://github.com/phillbush/xmenu/) or [dmenu](http://tools.suckless.org/dmenu/) to list and restore the minimized windows.

**Comment by blk750** [comment]
oh
